---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Restore cached dependencies (Javascript)
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: node-modules-${{ hashFiles('package.json') }}
      - name: Restore cached dependencies (Rust)
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: cargo-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Install WASM utils
        run: cargo install wasm-bindgen-cli wasm-tools wasm-opt
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Run Tests
        run: pnpm run ci
