name: Release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'The semver to use'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - prerelease
          - prepatch
          - preminor
          - premajor
      tag:
        description: 'The npm tag'
        required: false
        default: 'latest'
      commit-message:
        description: 'The commit message template'
        required: false
        default: 'Release {version}'
      prerelease:
        description: 'The prelease prefix'
        required: false
        default: 'beta'
        type: choice
        options:
          - alpha
          - beta
          - rc
  pull_request:
    types: [closed]
    branches:
      - main
      - 'release/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: node-modules-${{ hashFiles('package.json') }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Release
        uses: nearform/optic-release-automation-action@v4
        with:
          npm-token: ${{ secrets[format('NPM_TOKEN_{0}', github.actor)] || secrets.NPM_TOKEN }}
          optic-token: ${{ secrets[format('OPTIC_TOKEN_{0}', github.actor)] || secrets.OPTIC_TOKEN }}
          commit-message: ${{ github.event.inputs.commit-message }}
          semver: ${{ github.event.inputs.semver }}
          npm-tag: ${{ github.event.inputs.tag }}
          prerelease-prefix: ${{ github.event.inputs.prerelease }}
          version-prefix: 'v'
          build-command: |
            pnpm install
            pnpm run build
