name: wasm

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Compile Rust to WebAssembly with Docker
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1 

    runs-on: ${{ matrix.os }}
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
    
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.enginesHash }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1 

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ matrix.os }}-buildx-${{ hashFiles('**/Dockerfile') }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          build-contexts: rust=rust
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          load: true
          tags: lyrasearch/lyra-wasm
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Create Wasm artifacts
        run: |
          docker create --name tmp lyrasearch/lyra-wasm
          docker cp tmp:/opt/app/src/wasm ./src/wasm
          docker rm -f tmp

      - name: Show Wasm artifacts
        run: ls -l ./src/wasm
